Refactory/account payroll
abgfbr/odoo-brazil-hr pull request #169
Opened 2019-02-12 18:56 UTC by hendrixcosta

2019-02-19 18:40 UTC, lfdivino requested changes

2019-02-19 18:40 UTC, lfdivino commented on l10n_br_hr_payroll_account/models/hr_payslip_run.py
> +                'data': '2019-01-01',
Aqui era para estar hardcoded mesmo?

2019-02-20 11:33 UTC, lfdivino approved these changes

2019-02-20 11:39 UTC, lveras approved these changes

2019-02-20 11:44 UTC, merged