[WIP] Módulo de benefícios
abgfbr/odoo-brazil-hr pull request #303
Opened 2019-07-29 18:06 UTC by mileo

Signed-off-by: Luis Felipe Mileo <mileo@kmee.com.br>

2019-08-01 19:40 UTC, lfdivino commented on l10n_br_hr_benefit/models/hr_benefit_type.py
> +                ('name', '=', self.name),
Só pelo name não fica uma verificação muito frágil? Por ex.: ABC é diferente de ABC2

2019-08-01 19:48 UTC, mileo commented on l10n_br_hr_benefit/models/hr_benefit_type.py
> +                ('name', '=', self.name),
Esse modelo vai ser modificado e os campos de data vão para um relacional. Assim como esta função

2019-08-01 19:49 UTC, mileo commented on l10n_br_hr_benefit/models/hr_benefit_type.py
> +                ('name', '=', self.name),
Provavelmente uma estrutura similar a esta odoo/parts/addons/hr/hr_employee_benefit/models/hr_employee_benefit_rate.py

2019-08-01 19:52 UTC, lfdivino requested changes

2019-08-01 19:52 UTC, lfdivino commented on l10n_br_hr_benefit/models/hr_employee_dependent.py
> +    # has_changes = fields.Boolean(
@sadamo retirar estes códigos comentados.

2019-08-02 14:28 UTC, hendrixcosta approved these changes

2019-08-02 14:28 UTC, lfdivino approved these changes

2019-08-02 14:28 UTC, merged