[NEW] dependent as res.partner
abgfbr/odoo-brazil-hr pull request #304
Opened 2019-07-30 15:10 UTC by sadamo

Signed-off-by: Luis Felipe Mileo <mileo@kmee.com.br>

2019-07-30 16:40 UTC, hendrixcosta commented
O campo "dependent_name" deixou de existir?

2019-07-30 20:27 UTC, hendrixcosta requested changes
depende do https://github.com/abgfbr/l10n-brazil/pull/284

2019-08-01 19:47 UTC, hendrixcosta approved these changes

2019-08-01 19:52 UTC, lfdivino approved these changes

2019-08-02 13:48 UTC, merged